#!/usr/bin/sh

wkdir=/staging/reserve/paylong_ntu/AI_SHARE/GitHub/Germline_variant/Sentieon
SampleList=${wkdir}/../A1_Panel/test_ID.txt
PIPELINE=${wkdir}/variant_calling.sh
DAY=`date +%Y%m%d`

while read -r ID; 
	do
	cd ${wkdir}
	mkdir -p ${ID}
	cd ${wkdir}/${ID}
	rsync ${PIPELINE} ./${DAY}_Sentieon_pipeline_${ID}.sh 
	sed -i "s|SAMPLE_NAME|${ID}|g" ./${DAY}_Sentieon_pipeline_${ID}.sh
	
	sbatch ./${DAY}_Sentieon_pipeline_${ID}.sh
	sleep 3s
	cd ${wkdir}
	done<${SampleList}
